Add `source_range` method to `NodePattern`
Follow up https://github.com/rubocop/rubocop/pull/11630.

This PR provides a shorthand for `source_range` to `NodePattern`, like `RuboCop::AST::Node#source_range`.
It will make a consistent rewrite of `loc.expression` to `source_range`. And resolves the following errors.

```console
% bundle exec rake
(snip)

Failures:

  1) RuboCop::AST::NodePattern::Parser sequences parses simple sequences properly
     Failure/Error: expr = children.first.source_range.join(children.last.source_range)

  NoMethodError: (-) undefined method `source_range' for s(:node_type, :int):RuboCop::AST::NodePattern::Node
  # ./lib/rubocop/ast/node_pattern/with_meta.rb:56:in `emit_list'
  # ./lib/rubocop/ast/node_pattern/parser.racc.rb:306:in `_reduce_3'
  # (eval):3:in `_racc_do_parse_c'
  # (eval):3:in `do_parse'
  # ./lib/rubocop/ast/node_pattern/with_meta.rb:102:in `do_parse'
  # ./lib/rubocop/ast/node_pattern/parser.rb:33:in `parse'
  # ./spec/rubocop/ast/node_pattern/parse_helper.rb:94:in `try_parsing'
  # ./spec/rubocop/ast/node_pattern/helper.rb:20:in `expect_parsing'
  # ./spec/rubocop/ast/node_pattern/parser_spec.rb:10:in `block (3 levels) in <top (required)>'
```